# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MwzmudmRPA3yGjkoxK8/nyVSG9pQm4kQYIr31Uu6DQADB5Dt3H+A9YRuq+EvFXrQbDRB4Zayi9s67qFOXpKP0W3YwfGH6AZNDO66NhkNUKiyzod547s1RHoNTDjX62PZyzr2EPbbivgBGV5XFyKYfl39FwHcczVe4xze09i5RX6wy4NHnKnPt11vM1QNUu8m9J1NcR7DLcSzNUyICLXzha1K0eIGXfivN68NXy3ICQn0dd/u6tnfm0e0QBdtGulS2oujrBtcuzK6MJ60QLjCuv/IC2Z0TOlCDZ0FMFxyAdJ+v09tWotE2BhNE6P0mbEueAZiAVhahJ9Docdvap/TniqtVOKlCTfjKoHIA1kCejU7ploG1EnGkzBIwfm/M+Bc13SS7xFwqIQ6mcNRjXWtLho401ucSz2QDDcalaBj6u7SK1ZZHSsqs2P/x+qt4v070a2c8ig7BWjLPKDwzHoKE8rXxQYhQiQTrLfNeB1vx0qtRBobKCph5FMEY9VlR45Y1iATOlj8dJvH5dgUGf4Z/Ioje/rT2RAjoBjHnJ1FRFDs+3nJTRKPeA+OUdtkEt1Y2btcevAKDSTXO/kklVhDKvNr+6tI/n0JpIso5lhHn0gWk/ELWWQE5jzHuk9H8z4sFkdKfIVgSJ2fbSliuxfG7QtIKzKB4glf6czQSXoHxwM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
