travis:
  secure:
    BINSTAR_TOKEN: XoeuZpdcDriJXrmb4Ivu06563c9OLA0HxuEHLejVax2TYFTV5Xc4zSxPmT5Bk/jt/soM0I5fF2R22Z4E8h7SS6UEDahkgxW1yg7T9YaDXotKmpYn8ov88ZJmlUJC8DuQA5GGpidaqX0mV6zfCu8PBYkRc0kn1lqbXOZ8ftgnQEqo0GR4jRyiIgFgi+I7tTVurjUgiaP1rKq1QxrWRE1nSUVfI7DxVw/PpUtSwE1dVCsD7rxMaztWtB288Eiue/2nhC2dkdkouKsPlmm6HtazRn0v19OPQWV9xG7xIBC/EIvTOwErFSJddRYVvFahnFcuCG0Nnh4A1EoKWUt3pnz5U5jNcKoAfxRCvMvvd7i9zlVuzV3bT1z/1L/CU7kEmWH5eCiJxBhToOdn2ltZ7KqtrC0EbvyrWSCoCuYFdPEP1W+RnvSJy6br8G1HaMRca8ufnzEAWsgIPVljc5Is8RzhZLykq1bZf1TqERBqSh8y+wgvkz5LjsQUXGRcZX5adVhus4H693N15vUEaCK9GTmBg8M6YMGquUBYY2ZFwWdhlvLpy2zgEDhOLyVj1bvGpHrRk1IG/xnwiv9M0nm/cE99QIV5LUf8DSBRGU1r/oD4/FlI+VAMcZz2bqjSwK7vgoW4kFUkpYB7hghj0F92dwiYLO9KRy23WMbIv2IWNDsMSk8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
