travis:
  secure:
    BINSTAR_TOKEN: LKwwtkxUXgZ6OBw0ywAW0AMera5JPq0lpS4o94RV/nTaTHj4W4BP2OKLJM+9jDMr2pjWBg062giiXvrzYFyHLiPxKbpBYfcbDa5FfmieflXRiwe58IKc67pzMy4EYUVLTReCFQBJSF27jAGsqcxEkoPNB1H8uQF+66qAv7+cxhhxDLEzCXpoKX+VILwPkmHXOwAJkV50TzX9fVjEH6DvzYHxD6d32Vd3EnivJv3JmlgGhaUexOo4TdUz9/+N0FbR+uTHeG+wZfTBjeWR37ZT4bv6A5rFni8VwludZvA2RDJxHLtqfo7tPlRw9lUgSaxb+WnWtsFfImA56LIu0hc3DfYVEgnzCSq3HjllwazsDY7IiPUU3AvvAetp06MuupEStB4Kunp0umEJDvNXbkYqdap+fIPr98kVDtop3NfhqL+cJhelO4r/CsQDQwvReAsTuaMv8jWvdJ7IvbonHl4GKUcLcLy3WuKlMt3wRT+7pAK4un16pnLVRkVmm/14IJybPe8GX5Cdg/kJGBy4jm309THtTY1D7hAduQ8BCnTWMpQhxKtsgSDakYFB5w2sMeA/N+NLSwnn8kMDC/Zc/+wkQlCthVCWhZMckcggYkNfJLiM2lwrTwkm65Akij7y9tVkf7jmo/WeYsSTDxrzOB+55ai7INdoBKA37xJefEdSMvc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
