travis:
  secure:
    BINSTAR_TOKEN: VFD3m7Qac4xFFlDNlP8EGUX8K+1d9b7rD2paWnMZs1rIGPpfo1hN91yfB0Zf7q64pcTe1bR3aBYuVHgQe9EPCE7UIgEnRV0p80G2COEdVpOd6qVBgb2Cz6Bk6Tl5lCQjN4FwAXUXrMplZgMrOm6In893OZuJzh4ImNPrDawx9psWMcyvxxnImqeQCInxM+lKqQsblOZOvnovujim1fR8qDlO/rDE7RBZ7QbRrxao5QP1jq12up1jNWOjf5OsFhdHbpP2UKe1rH27SZnwHsbpGz5KKPGjyWm/0iHlsbXAoub/+/Y6HkrxR2DHk5Ff9eUPiWyhz5j7s6aditOxjPDgoruYcNygPkKtiJnWS9SXNx+/htx6rW+wJkSPCWsCh6lRg/NFPI5ZcvzzeKRWbMsWpGOMpfp6XkUqarUo6/x72EJyVeqfHqGmwKIXyQtRHvs/5aOECjCAmisA3QmDXzKO64/lQFRn/sd9MLYFXJFOGLFCPCHFuAC724Pp2il9ExG+EforZxtPUZIznKzKswd6CvcUmXSWmfZ402lc4BFEUcw4f1YHdnA20+oSlVVuk3m5g5TRRqJyWtzblzQKYdVSyFU1olm4Q6N/6lA7cyMHsdyZ2lhRAOmhFyDngyHRqmY9+IoEQg2Ztr3AmhNLp4IW4nfTBr8/sM6h8UNpnY/Zqlg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
